apiVersion: v1
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    app: demo-voting-app
kind: Pod
spec:
   containers:
      - name: postgres
        image: postgres
        ports:
          - containerPort: 5432