apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  selector:
    app: demo-voting-app
    name: redis-pod
  ports:
    port: 6379
    targetPort: 6379