apiVersion: apps/v1
kind: Deployment
metadata:
		name: result-deployment
		labels:
			app: demo-voting-app
spec:
	selector:
		matchLabels:
			app: demo-voting-app
			name: result-pod
	replicas: 1
	template:
		metadata:
			name: result-app-pod
			labels:
				name: result-app-pod
				app: demo-voting-app
		spec:
			containers:
				- name: result-app
				  image: dockersamples/exampledemovoting_result
				  ports:
						- containerPort: 80