apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app
spec:
  type: LoadBalancer
  selector:
    app: demo-voting-app
    name: result-app-pod
  ports:
    - port: 80
      targetPort: 80